
export type Language = 'pt' | 'en' | 'es';

export interface Ingredient {
  item: string;
  amount: string;
  note?: string;
  purchaseLink?: string; // Optional link for "Shop the ingredients"
}

export interface NutritionInfo {
  calories: number;
  protein: string;
  carbs: string;
  fat: string;
}

export interface AffiliateProduct {
  name: string;
  url: string;
  price?: string;
  imageUrl?: string; // Optional image for equipment
}

export interface Review {
  id: string;
  author: string;
  rating: number; // 1-5
  comment: string;
  date: string;
}

export interface FAQItem {
  question: string;
  answer: string;
}

export interface Recipe {
  id: string;
  title: string;
  slug: string; // For SEO: preserves the wordpress slug
  datePublished: string; // ISO Date (YYYY-MM-DD) - Crucial for Google
  originalLink?: string; // To track where it came from
  description: string; // Short summary
  story: string; // The "blog post" part
  prepTime: string;
  cookTime: string;
  totalTime?: string; // Optional total time display
  servings: number;
  ingredients: Ingredient[];
  steps: string[];
  nutrition: NutritionInfo;
  imageUrl: string;
  videoUrl?: string; // YouTube URL
  affiliates: AffiliateProduct[];
  tags: string[];
  status?: 'published' | 'draft';
  reviews?: Review[]; // Optional initial reviews
  tips?: string[]; // Chef secrets/troubleshooting
  pairing?: string; // Drink recommendation
  faq?: FAQItem[]; // Common questions generated by AI
}

// Web Stories Structure
export interface StorySlide {
  type: 'cover' | 'ingredients' | 'step' | 'conclusion';
  layout: 'classic' | 'modern' | 'quote' | 'minimal' | 'cover' | 'list' | 'conclusion'; // New: Layout style
  text: string;
  subtext?: string;
  imageUrl: string; 
  visualPrompt?: string; // To generate unique images per slide
}

export interface WebStory {
  id: string;
  recipeId: string;
  title: string;
  slides: StorySlide[];
}

// Reels Structure
export interface ReelScript {
  hook: string; // 0-3s text
  body: string; // Main script
  cta: string; // Call to action
  visualPrompt: string; // Prompt for Veo video generation
  hashtags: string;
}

// Structure for raw data coming from WordPress
export interface WordPressPost {
  id: number;
  date: string;
  slug: string;
  title: { rendered: string };
  content: { rendered: string };
  excerpt: { rendered: string };
  link: string;
}

export interface AdSettings {
  clientId: string; // ca-pub-XXXXXXXXXXXXXXXX
  slots: {
    homeTop: string;
    homeMiddle: string;
    sidebar: string;
    recipeTop?: string;    // New
    recipeMiddle?: string; // New
    recipeBottom?: string; // New
  };
}

// NutriScanner Analysis Result
export interface NutritionalAnalysis {
  foodName: string;
  calories: number;
  protein: string;
  carbs: string;
  fat: string;
  healthTip: string;
}

// Dynamic Category
export interface Category {
  id: string;
  name: string;
  img: string;
}

// Global Site Settings
export interface SiteSettings {
  siteName: string;
  siteDescription: string;
  heroRecipeIds: string[]; // IDs of recipes to rotate in Hero
  n8nWebhookUrl?: string; // URL for n8n Affiliate Workflow
  n8nSocialWebhookUrl?: string; // NEW: URL for n8n Social Media Workflow
  socialLinks: {
    facebook?: string;
    instagram?: string;
    twitter?: string;
    youtube?: string;
  }
}

// Chatbot Types
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  text: string;
  isTyping?: boolean; // For UI state
  showLeadGen?: boolean; // Trigger the lead capture form
}
